import libs = yaml-cpp%lib{yaml-cpp}
import libs += gtest%lib{gtest}
import libs += gmock%lib{gmock}

exe{yaml-cpp-tests}: test/{hxx cxx}{**} $libs

cxx.poptions =+ "-I$src_base/src_private_headers" "-I$src_base/test" "-I$out_root" "-I$src_root"
