pub_hdrs = {hxx ixx txx}{**}

./: $pub_hdrs

hxx{export}@./: cxx.importable = false

# Install recreating subdirectories.
#
{hxx ixx txx}{*}:
{
  install         = include/
  install.subdirs = true
}
