./ : lib{yaml-cpp}

lib{yaml-cpp}: include/hxx{**} hxx{version}
lib{yaml-cpp}: src/cxx{**}

hxx{version} : in{version} $src_root/manifest
{
  dist  = true
  clean = ($src_root != $out_root)
  install = include/yaml-cpp
}

# Build options.
cxx.poptions =+ "-I$src_base/include" "-I$out_root" "-I$src_root"
cxx.poptions += -DYAML_CPP_STATIC_DEFINE

# Export options.
lib{yaml-cpp}:
{
  cxx.export.poptions = "-I$src_base/include" "-I$out_root" "-I$src_root"
}
libs{yaml-cpp}: cxx.export.poptions += -DYAML_CPP_STATIC_DEFINE

if $version.pre_release
  lib{yaml-cpp}: bin.lib.version = @"-$version.project_id"
else
  lib{yaml-cpp}: bin.lib.version = @"-$version.major.$version.minor"

include/
{
  {hxx ixx txx}{*}:
  {
    install         = include/
    install.subdirs = true
  }
}